### ISSUE TITLE
请问下market details是什么数据？

### ISSUE THREAD

**Issue by kitoytimmy** [hbdmapi/huobi_futures_CSharp#1]
请问下market details是什么数据？

如下几个问题
1）数据是实时推送吗？是否有成交即推送？

2）open close low high amount vol count是什么周期的数据？
我对比了下windows客户端，好像details 里面的这些字段和日线数据字段一致，是否正确？

3）tick.id定位的是分钟？

4）为什么每一分钟vol count会变小一次？推送的vol count 到底代表什么时间段或者周期的数据？为什么不是持续增加了？
如果是按分钟周期，为什么只是变小再增加，而不是归零再增加？
ts:1615789020225 2021-03-15T14:17:00 225 id:1615789020 2021-03-15T14:17:00 0 details count小于前一数据，pre:1019433 current:1018904
ts:1615789020225 2021-03-15T14:17:00 225 id:1615789020 2021-03-15T14:17:00 0 details vol小于前一数据，pre:284621466 current:284544014
ts:1615789080225 2021-03-15T14:18:00 225 id:1615789080 2021-03-15T14:18:00 0 details count小于前一数据，pre:1019534 current:1018914
ts:1615789080225 2021-03-15T14:18:00 225 id:1615789080 2021-03-15T14:18:00 0 details vol小于前一数据，pre:284666686 current:284551638
ts:1615789140225 2021-03-15T14:19:00 225 id:1615789140 2021-03-15T14:19:00 0 details count小于前一数据，pre:1019442 current:1018868
ts:1615789140225 2021-03-15T14:19:00 225 id:1615789140 2021-03-15T14:19:00 0 details vol小于前一数据，pre:284674064 current:284573286
ts:1615789200225 2021-03-15T14:20:00 225 id:1615789200 2021-03-15T14:20:00 0 details count小于前一数据，pre:1019777 current:1017654
ts:1615789200225 2021-03-15T14:20:00 225 id:1615789200 2021-03-15T14:20:00 0 details vol小于前一数据，pre:284776660 current:284078022

**Comment by ad-long** [comment]
market detail和聚合行情是一样的数据
有关推送频率可以参考: https://docs.huobigroup.com/docs/usdt_swap/v1/cn/#ws 中Q10: WS中的market detail 和 trade detail 具体什么区别和含义?
和时间相关的id单位是秒
