### ISSUE TITLE
系统启动时，如果快速获取在线挂单。

### ISSUE THREAD

**Issue by kitoytimmy** [hbdmapi/huobi_futures_CSharp#2]
问题：
USDT本币永续目前有80个合约，还区分全仓和逐仓。
假如在启动前，账号中有挂单在线。
请问通过api如何快速知道？

1）RESTful获取OpenOrder中，参数contractCode不能为*只能一个一个获取；
2）Websocket订阅Order.* ,连接后不会推送当前在线挂单，只是有变化才推送；

国内期货api都有功能，要么能查询当前账号所以在线挂单，要么订阅时推送一次在线挂单。因为在线为成交单一般不会很多。
请问下，huobi api, 有啥方法，快速获取在线挂单，而不是一个个合约去查。

**Comment by ad-long** [comment]
目前只能一个contractCode一个contractCode的去查询, 暂时没有一次查询所有在线未成交单的接口.
对此功能我们会反馈记录
